[package]
name = "dim_wishlist_cleanup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# crates.io
[dependencies]
arbitrary = {version = "1.3.2", features = ["derive"]}
pest = "2.4.1"
pest_derive = "2.4.1"
