[package]
name = "dim_wishlist_cleanup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# crates.io
[dependencies]
pest = "2.4.1"
