name: "Deploy"

on:
  push:
    branches:
      - 'main'
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - name: Fetch the voltron file
        run: curl https://raw.githubusercontent.com/48klocs/dim-wish-list-sources/master/voltron.txt > voltron.txt

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

  run:
    name: Run and Push to S3
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch the voltron file
        run: curl https://raw.githubusercontent.com/48klocs/dim-wish-list-sources/master/voltron.txt > voltron.txt

      - run: cargo run > latest.txt

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && sudo ./aws/install

# TODO Replace with https://github.com/marketplace/actions/configure-aws-credentials-for-github-actions#credentials
      # - name: Set env
      #   run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.ADMIN_ACCESS_KEY }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.ADMIN_SECRET_KEY }}
      #     AWS_DEFAULT_REGION: "us-east-1"
      
      
      - run: s3 put-object --bucket dsoif --key latest.txt
